---
# Use new travis-ci container-based infrastructure.
sudo: false

language: python

python:
    - "3.6"

# Install dependencies.
install:
    - pip install -r requirements.txt flake8 flake8-commas yamllint

# Run tests.
script:
    - flake8 jenkins_exporter.py --max-line-length=140 -v --ignore=
    - yamllint --strict .travis.yml
    - python test.py
