
language: python
python:
    - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt flake8 flake8-commas"
# command to run tests
script:
    - flake8 jenkins_exporter.py --max-line-length=140 -v --ignore=
    - python test.py
# use new travis-ci container-based infrastructure
sudo: false
